spring.application.name=theory_saga
server.port=8095

services.theory-organization.url=${SERVICES_THEORY_ORGANIZATION_URL:http://localhost:8090}
services.theory-search.url=${SERVICES_THEORY_SEARCH_URL:http://localhost:8092}
