
services:
  neo4j-mila:
    image: neo4j:latest
    container_name: neo4j-mila
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password123
    volumes:
      - ./neo4j_mila_data:/data
    networks:
      - autoskola-network

  class-organization:
    build:
      context: ./class-organization
    container_name: class-organization-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_NEO4J_URI=bolt://neo4j-mila:7687
      - SPRING_NEO4J_AUTHENTICATION_USERNAME=neo4j
      - SPRING_NEO4J_AUTHENTICATION_PASSWORD=password123
    depends_on:
      - neo4j-mila
    networks:
      - autoskola-network

  neo4j-sara:
    image: neo4j:latest
    container_name: neo4j-sara
    ports:
      - "7480:7474"
      - "7690:7687"
    environment:
      - NEO4J_AUTH=neo4j/sara123!
    volumes:
      - ./neo4j_sara_data:/data
    networks:
      - autoskola-network

  theory-organization:
    build:
      context: ./theory_organization
    container_name: theory-organization-service
    ports:
      - "8090:8090"
    environment:
      - SPRING_NEO4J_URI=bolt://neo4j-sara:7687
      - SPRING_NEO4J_AUTHENTICATION_USERNAME=neo4j
      - SPRING_NEO4J_AUTHENTICATION_PASSWORD=sara123!
      - SERVER_PORT=8090
    depends_on:
      - neo4j-sara
    networks:
      - autoskola-network


  # TANJA: BAZA
  neo4j-tanja:
    image: neo4j:latest
    container_name: neo4j-tanja
    ports:
      - "7475:7474"
      - "7688:7687"
    environment:
      - NEO4J_AUTH=neo4j/password123
    volumes:
      - ./neo4j_data_tanja:/data
      - ./neo4j_logs_tanja:/logs
    networks:
      - autoskola-network

  # TANJA: Instructor Management
  instructor-management:
    build: ./instructor-management
    container_name: instructor-management-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_NEO4J_URI=bolt://neo4j-tanja:7687
      - SPRING_NEO4J_AUTHENTICATION_USERNAME=neo4j
      - SPRING_NEO4J_AUTHENTICATION_PASSWORD=password123
      - SERVER_PORT=8080
    depends_on:
      - neo4j-tanja
    networks:
      - autoskola-network

  elasticsearch-mila:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch_db
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false 
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" 
    ports:
      - "9209:9200"
    networks:
      - autoskola-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
 
  practical-class-es:
    build:
      context: ./practical-class-es 
      dockerfile: Dockerfile
    container_name: practical_class_es_app
    ports:
      - "8085:8080" 
    environment:
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch-mila:9200
      - SPRING_DATA_REDIS_HOST=redis-mila
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      elasticsearch-mila:
        condition: service_healthy
      redis-mila:
        condition: service_healthy
    networks:
      - autoskola-network

  redis-mila:
      image: redis:7-alpine
      container_name: redis-mila
      ports:
        - "6380:6379"
      networks:
        - autoskola-network
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 10s
        timeout: 5s
        retries: 5

networks:
  autoskola-network:
    driver: bridge